//Script GUID:3d4eb78a-de64-46dd-b9d8-90b8648962e7
//Used for tracking history
ulsStream = SSTREAM "shares/WacStructured.prod/local/structured/uls_by_tag/?date=2014-07-30...2014-08-01";

search = 
    SELECT MyHelper.DateTimeToQuanta(TimeStamp) AS Quanta
    FROM ulsStream;

count = 
    SELECT COUNT(*) AS countNum
    FROM search;

OUTPUT count
TO SSTREAM "/local/shuywang/output.ss"
WITH STREAMEXPIRY "1";